webhook/main/default/objects/Outbound_Webhook__e/Outbound_Webhook__e.object-meta.xml
<CustomObject>
    <description>This particular event represents event that will fire a webhook to subscribers</description>
    <label>Outbound Webhook</label>
    <pluralLabel>Outbound Webhooks</pluralLabel>
</CustomObject>

webhook/main/default/objects/Outbound_Webhook__e/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>This is be matched with the webhook listener registration; only events with matching matching will be fired to the webhook url</description>
    <label>Event Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

webhook/main/default/objects/Webhook_Event_Setting__mdt/Webhook_Event_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Stores the event body processor class name for particular event type. This alters the content data when get one template api is called. Body processor must implement NTFH_NotificationTemplate.BodyProcessor interface.</description>
    <label>NTFH Webhook Event Body Processor</label>
    <pluralLabel>NTFH Webhook Event Body Processors</pluralLabel>
</CustomObject>

webhook/main/default/objects/Webhook_Event_Setting__mdt/fields/Body_Processor_Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Body_Processor_Apex_Class_Name__c</fullName>
    <label>Body Processor Apex Class Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

webhook/main/default/objects/Webhook_Event_Setting__mdt/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

webhook/main/default/objects/Webhook_Registration__c/Webhook_Registration__c.object-meta.xml
<CustomObject>
    <description>Represents a subscriber to a webhook event. This object should be access/modified via api</description>
    <label>Webhook Registration</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Webhook Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webhook Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

webhook/main/default/objects/Webhook_Registration__c/fields/Callback_Url__c.field-meta.xml
<CustomField>
    <fullName>Callback_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Callback Url</label>
    <type>TextArea</type>
</CustomField>

webhook/main/default/objects/Webhook_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Type of event that is subscribed. This is matched the Event Type on the Outbound Webhook platform event</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Event</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

webhook/main/default/objects/Webhook_Registration__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <description>represents the serialized custom Http headers to be sent with the webhook</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Header</label>
    <type>TextArea</type>
</CustomField>

webhook/main/default/objects/Webhook_Registration__c/fields/Shared_Secret__c.field-meta.xml
<CustomField>
    <fullName>Shared_Secret__c</fullName>
    <description>Generated shared secret at subscribe time used to sign webhook data body.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Shared Secret</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

webhook/main/default/objects/Webhook_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

webhook/main/default/objects/Webhook_Settings__c/Webhook_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global webhook settings; Use org default to alter value.</description>
    <label>Webhook Settings</label>
</CustomObject>

webhook/main/default/objects/Webhook_Settings__c/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <description>The batch size to fire webhook batch.</description>
    <inlineHelpText>Reduce this number if encountering heap size / apex timeout issue from callout batch. Maximum is based on callout limit per transaction(100)</inlineHelpText>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

webhook/main/default/classes/Outbound/OutboundWebhook.cls
/**
 * @description entry point to get all parameter need to start the callout batch for a (set of) Outbound_Webhook__e platform events
 * @author Andi Xie
 */
public with sharing class OutboundWebhook {
    static final Integer MAX_BATCH_SIZE = 100;
    static final String WEBHOOK_EVENT_LISTENER_STATUS_ACTIVE = OutboundWebhookRegistration.REGISTRATION_STATUS_ACTIVE;
    @TestVisible
    private static List<Outbound_Webhook__e> eventsReceived = new List<Outbound_Webhook__e>();
    Map<String, List<Webhook_Registration__c>> eventNameToListenerMap;
    Map<String, List<Outbound_Webhook__e>> eventNameMap;
    List<Outbound_Webhook__e> events;
    Map<String, Webhook_Event_Setting__mdt> eventNameToSettingMap;

    /**
     * @description Constructor to get relavent subscriber and event specific settings
     * @param  events events fired
     */
    public OutboundWebhook(List<Outbound_Webhook__e> events) {
        Set<String> eventNames = new Set<String>();
        Map<String, List<Webhook_Registration__c>> eventNameToListenerMap = new Map<String, List<Webhook_Registration__c>>();
        Map<String, List<Outbound_Webhook__e>> eventNameMap = new Map<String, List<Outbound_Webhook__e>>();
        Map<String, Webhook_Event_Setting__mdt> eventNameToSettingMap = new Map<String, Webhook_Event_Setting__mdt>();

        for (Outbound_Webhook__e event : events) {
            String type = event.Event_Type__c;
            if (eventNames.contains(type)) {
                List<Outbound_Webhook__e> eventList = eventNameMap.get(type);
                eventList.add(event);
                continue;
            }
            eventNames.add(type);
            eventNameToListenerMap.put(type, new List<Webhook_Registration__c>());
            eventNameMap.put(type, new List<Outbound_Webhook__e>{ event });
            eventsReceived.add(event);
        }

        List<Webhook_Registration__c> applicableListeners = [
            SELECT Callback_Url__c, Shared_Secret__c, Event__c, Header__c
            FROM Webhook_Registration__c
            WHERE Event__c IN :eventNames AND Status__c = :WEBHOOK_EVENT_LISTENER_STATUS_ACTIVE 
            WITH SECURITY_ENFORCED
        ];
        for (Webhook_Registration__c listener : applicableListeners) {
            List<Webhook_Registration__c> regList = eventNameToListenerMap.get(listener.Event__c);
            regList.add(listener);
        }
        this.eventNameToListenerMap = eventNameTOListenerMap;
        this.eventNameMap = eventNameMap;
        this.events = events;
        loadBodyProcessor();
    }

    private void loadBodyProcessor() {
        for (Webhook_Event_Setting__mdt setting : [
            SELECT Body_Processor_Apex_Class_Name__c, Event_Type__c
            FROM Webhook_Event_Setting__mdt
            WHERE Event_Type__c IN :eventNames
            WITH SECURITY_ENFORCED
        ]) {
            if (setting.Body_Processor_Apex_Class_Name__c == null) {
                continue;
            }
            eventNameToSettingMap.put(setting.Event_Type__c, setting);
        }

        this.eventNameToSettingMap = eventNameToSettingMap;
    }

    /**
     * @description entry method to start the callout batch job
     */
    public void startCallOutBatch() {
        OutboundWebhookBatch batch = new OutboundWebhookBatch(events, eventNameToListenerMap, eventNameToSettingMap);
        Database.executeBatch(batch, getBatchSize());
    }

    Integer getBatchSize() {
        Integer orgSettingBatchSize = Webhook_Settings__c.getOrgDefaults().Batch_Size__c == null
            ? MAX_BATCH_SIZE
            : (Integer) Webhook_Settings__c.getOrgDefaults().Batch_Size__c;
        return orgSettingBatchSize > MAX_BATCH_SIZE ? MAX_BATCH_SIZE : orgSettingBatchSize;
    }
}